### ISSUE TITLE
Some placeholders having minimessage closing tags that were not like turned back into components properly?

### ISSUE THREAD

**Issue by Xemorr** [lucypoulton/papi-kyorify#5]
"&c&l&ki&6&l&k1&r&8&l[&e&l2&a&l0&b&l2&9&l2&8&l]&5&l&k1&r&d&l&ki&r" is a placeholder for a certain tag we have, it is inside a kyorify and becomes that in chat when passed to ChatChat. Any ideas?
![image](https://user-images.githubusercontent.com/31805746/181921134-1aabc3c9-009b-46d8-a7b9-499f41a6b369.png)

**Comment by lucypoulton** [comment]
Interesting, thanks for pointing this out. Will investigate.

**Comment by lucypoulton** [comment]
This turned out to be a bug in how `&r` is handled, I've just released version 1.5 addressing this.
